// ═══════════════════════════════════════════════════════════
// JOIAFLIX — Catálogo de Vídeos
// Todos os IDs verificados via YouTube oEmbed API (2026-04-04)
// ═══════════════════════════════════════════════════════════

const CATEGORIES = [
  { id: 'destaques', name: 'Em Destaque', icon: '⭐' },
  { id: 'ouro', name: 'Ouro', icon: '🥇' },
  { id: 'diamantes', name: 'Diamantes', icon: '💎' },
  { id: 'prata', name: 'Prata & Metais', icon: '🪙' },
  { id: 'joalheria', name: 'Joalheria & Artesanato', icon: '💍' },
  { id: 'mineracao', name: 'Mineração & Garimpo', icon: '⛏️' },
  { id: 'mercado', name: 'Mercado & Investimento', icon: '📈' },
  { id: 'historia', name: 'História & Civilizações', icon: '🏛️' },
  { id: 'luxo', name: 'Marcas de Luxo', icon: '👑' },
  { id: 'gemologia', name: 'Gemologia & Pedras', icon: '🔬' },
  { id: 'filmes', name: 'Filmes', icon: '🎬' },
];

const VIDEOS = [

  // ═══════════════════════════════════════
  // OURO
  // ═══════════════════════════════════════
  {
    id: 'v001',
    title: 'Gold: A Journey With Idris Elba',
    description: 'Documentário completo do World Gold Council narrado por Idris Elba. Uma jornada pelo mundo do ouro: mineração, refino, mercado e o impacto nas comunidades.',
    youtubeId: 'R7UikzYdgTc',
    duration: '1h 05min',
    year: 2020,
    language: 'Inglês',
    subtitles: 'PT-BR (auto)',
    categories: ['destaques', 'ouro', 'mineracao'],
    rating: 4.7,
    source: 'World Gold Council',
  },
  {
    id: 'v002',
    title: 'The Golden Thread — A Nova Fronteira do Ouro',
    description: 'Episódio 1 da série do World Gold Council sobre o futuro da indústria do ouro: tecnologia, sustentabilidade e inovação na mineração.',
    youtubeId: 'WqML1-oYU98',
    duration: '30 min',
    year: 2021,
    language: 'Inglês',
    subtitles: 'PT-BR (auto)',
    categories: ['ouro', 'mineracao'],
    rating: 4.5,
    source: 'World Gold Council',
  },
  {
    id: 'v003',
    title: 'Gold Mafia — O Serviço de Lavanderia (Ep. 1)',
    description: 'Investigação da Al Jazeera sobre a máfia do ouro: contrabando, lavagem de dinheiro e corrupção no comércio global de ouro na África.',
    youtubeId: 'evWEuVR1XIs',
    duration: '48 min',
    year: 2023,
    language: 'Inglês',
    subtitles: 'PT-BR (auto)',
    categories: ['destaques', 'ouro', 'mineracao', 'mercado'],
    rating: 4.8,
    source: 'Al Jazeera Investigations',
  },
  {
    id: 'v004',
    title: 'Money vs Currency — Os Segredos Ocultos do Dinheiro',
    description: 'Mike Maloney explica a diferença entre dinheiro e moeda, o papel do ouro no sistema financeiro e por que o ouro é a reserva de valor definitiva.',
    youtubeId: 'DyV0OfU3-FU',
    duration: '30 min',
    year: 2013,
    language: 'Inglês',
    subtitles: 'PT-BR (auto)',
    categories: ['ouro', 'mercado'],
    rating: 4.6,
    source: 'GoldSilver',
  },
  {
    id: 'v005',
    title: 'Por Que Bancos Centrais Estão Acumulando Ouro',
    description: 'Análise sobre a corrida dos bancos centrais pelo ouro: China, Rússia, Índia e a desdolarização. O que isso significa para investidores.',
    youtubeId: 'DKZmHOhzy4U',
    duration: '30 min',
    year: 2023,
    language: 'Inglês',
    subtitles: 'PT-BR (auto)',
    categories: ['ouro', 'mercado'],
    rating: 4.5,
    source: 'GoldSilver',
  },
  {
    id: 'v006',
    title: 'Thomas Edison na Corrida do Ouro do Klondike',
    description: 'Imagens raras e surpreendentes filmadas por Thomas Edison durante a corrida do ouro no Klondike. Arquivo histórico restaurado pelo Smithsonian.',
    youtubeId: 'LPTWJ1BNCio',
    duration: '12 min',
    year: 2019,
    language: 'Inglês',
    subtitles: 'PT-BR (auto)',
    categories: ['ouro', 'historia'],
    rating: 4.4,
    source: 'Smithsonian Channel',
  },
  {
    id: 'v007',
    title: 'Gold Rush — A Febre do Ouro Moderna',
    description: 'Como garimpeiros modernos arriscam tudo na busca pelo ouro em regiões remotas do mundo. Tecnologia vs. métodos tradicionais.',
    youtubeId: 'ASSOQDQvVLU',
    duration: '48 min',
    year: 2022,
    language: 'Inglês',
    subtitles: 'PT-BR (auto)',
    categories: ['ouro', 'mineracao'],
    rating: 4.5,
    source: 'Free Documentary',
  },
  {
    id: 'v008',
    title: 'A Rota do Ouro — Do Garimpo à Barra',
    description: 'O caminho que o ouro percorre desde a mina até se tornar uma barra de 400 onças em um cofre de banco central.',
    youtubeId: 'CTtf5s2HFkA',
    duration: '45 min',
    year: 2021,
    language: 'Inglês',
    subtitles: 'PT-BR (auto)',
    categories: ['ouro', 'mercado'],
    rating: 4.6,
    source: 'VICE',
  },

  // ═══════════════════════════════════════
  // DIAMANTES
  // ═══════════════════════════════════════
  {
    id: 'v101',
    title: 'The Diamond Empire — O Monopólio De Beers',
    description: 'O clássico documentário da PBS Frontline sobre como a De Beers criou o mercado de diamantes e a ilusão de escassez. Obrigatório para quem trabalha no setor.',
    youtubeId: 'Pr760mRwek4',
    duration: '1h 54min',
    year: 1994,
    language: 'Inglês',
    subtitles: 'PT-BR (auto)',
    categories: ['destaques', 'diamantes', 'mercado', 'historia'],
    rating: 4.9,
    source: 'PBS Frontline',
  },
  {
    id: 'v102',
    title: 'Diamantes de Laboratório São Melhores? — DW Planet A',
    description: 'A DW investiga: diamantes lab-grown vs. minerados. Impacto ambiental, ética, qualidade e o futuro da indústria.',
    youtubeId: 'bZhRjh3Vg7w',
    duration: '18 min',
    year: 2023,
    language: 'Inglês',
    subtitles: 'PT-BR (auto)',
    categories: ['destaques', 'diamantes', 'gemologia'],
    rating: 4.7,
    source: 'DW Planet A',
  },
  {
    id: 'v103',
    title: 'Diamantes de Sangue — República Centro-Africana',
    description: 'VICE News investiga o comércio de diamantes de conflito na África Central: guerra religiosa, contrabando e o Processo de Kimberley.',
    youtubeId: 'FbT_b0obeg8',
    duration: '20 min',
    year: 2016,
    language: 'Inglês',
    subtitles: 'PT-BR (auto)',
    categories: ['diamantes', 'mineracao'],
    rating: 4.5,
    source: 'VICE News',
  },
  {
    id: 'v104',
    title: 'Como Diamantes São Feitos — How It\'s Made',
    description: 'O processo completo de lapidação de diamantes: do bruto ao brilhante perfeito, com tecnologia de precisão laser.',
    youtubeId: 'xPuboJ0bEe4',
    duration: '5 min',
    year: 2020,
    language: 'Inglês',
    subtitles: 'PT-BR (auto)',
    categories: ['diamantes', 'joalheria'],
    rating: 4.6,
    source: 'How It\'s Made',
  },
  {
    id: 'v105',
    title: 'Mineração de Diamantes — Dentro da Maior Mina do Mundo',
    description: 'Tour pela maior mina de diamantes do mundo. Como se extrai diamante a centenas de metros de profundidade.',
    youtubeId: 'Z3IDnEOUIWM',
    duration: '20 min',
    year: 2021,
    language: 'Inglês',
    subtitles: 'PT-BR (auto)',
    categories: ['diamantes', 'mineracao'],
    rating: 4.4,
    source: 'Free Documentary',
  },
  {
    id: 'v106',
    title: 'Diamantes, Ouro e Ganância — História da África (BBC)',
    description: 'Episódio 18 da série da BBC sobre a história da África: como diamantes e ouro moldaram o continente, de Cecil Rhodes à De Beers.',
    youtubeId: 'fLL5xt2c-0I',
    duration: '25 min',
    year: 2020,
    language: 'Inglês',
    subtitles: 'PT-BR (auto)',
    categories: ['diamantes', 'ouro', 'historia'],
    rating: 4.6,
    source: 'BBC News Africa',
  },
  {
    id: 'v107',
    title: 'Diamantes Sintéticos — Documentário BBC',
    description: 'A BBC investiga a revolução dos diamantes sintéticos: como a ciência está desafiando o monopólio dos diamantes naturais.',
    youtubeId: 'dtPfBfTiHxo',
    duration: '45 min',
    year: 2018,
    language: 'Inglês',
    subtitles: 'PT-BR (auto)',
    categories: ['diamantes', 'gemologia'],
    rating: 4.5,
    source: 'BBC Documentary',
  },
  {
    id: 'v108',
    title: 'Índia: Diamantes em Guerra — ARTE',
    description: 'Documentário da ARTE sobre a indústria de diamantes na Índia: lapidação em massa, condições de trabalho e o comércio global.',
    youtubeId: 'AyhGIMlT36c',
    duration: '50 min',
    year: 2022,
    language: 'Inglês',
    subtitles: 'PT-BR (auto)',
    categories: ['diamantes', 'mercado'],
    rating: 4.4,
    source: 'ARTE Documentary',
  },

  // ═══════════════════════════════════════
  // PRATA & METAIS
  // ═══════════════════════════════════════
  {
    id: 'v201',
    title: 'Platina — Mineração, Ciência e História',
    description: 'Documentário completo sobre a platina: mineração na África do Sul, aplicações industriais, joalheria e por que é mais rara que o ouro.',
    youtubeId: 'NG2Y_GpNCds',
    duration: '40 min',
    year: 2020,
    language: 'Inglês',
    subtitles: 'PT-BR (auto)',
    categories: ['prata', 'mineracao'],
    rating: 4.4,
    source: 'Commodity Culture',
  },
  {
    id: 'v202',
    title: 'Anel de Prata Artesanal com Peridoto — Tutorial',
    description: 'O processo completo de fabricação artesanal de um anel em prata esterlina com pedra peridoto: soldagem, cravação e polimento.',
    youtubeId: 'fMspGMO0T9A',
    duration: '20 min',
    year: 2022,
    language: 'Inglês',
    subtitles: 'PT-BR (auto)',
    categories: ['prata', 'joalheria'],
    rating: 4.5,
    source: 'Kristina Bobin',
  },

  // ═══════════════════════════════════════
  // JOALHERIA & ARTESANATO
  // ═══════════════════════════════════════
  {
    id: 'v301',
    title: 'The Handmade Jewellers — Episódio 1',
    description: 'Série documental sobre joalheiros artesanais britânicos. Técnicas de bancada, design, soldagem e o ofício da joalheria à mão.',
    youtubeId: 'GjJILwa-2Oo',
    duration: '25 min',
    year: 2021,
    language: 'Inglês',
    subtitles: 'PT-BR (auto)',
    categories: ['destaques', 'joalheria'],
    rating: 4.8,
    source: 'Jewellers Academy',
  },
  {
    id: 'v302',
    title: 'The Handmade Jewellers — Episódio 2',
    description: 'Continuação da série: novos artesãos, técnicas de filigrana, esmaltação e o mercado de joias artesanais.',
    youtubeId: 'VR6UrYzDVqg',
    duration: '25 min',
    year: 2021,
    language: 'Inglês',
    subtitles: 'PT-BR (auto)',
    categories: ['joalheria'],
    rating: 4.7,
    source: 'Jewellers Academy',
  },
  {
    id: 'v303',
    title: 'The Handmade Jewellers — Episódio 3',
    description: 'Terceiro episódio da série: lapidação, cravação de pedras e o caminho do aprendiz ao mestre joalheiro.',
    youtubeId: 'qUCTVxw3BC0',
    duration: '25 min',
    year: 2021,
    language: 'Inglês',
    subtitles: 'PT-BR (auto)',
    categories: ['joalheria'],
    rating: 4.7,
    source: 'Jewellers Academy',
  },
  {
    id: 'v304',
    title: 'A Arte do Anel de Noivado — Da Mina ao Dedo',
    description: 'Todo o caminho: mineração, lapidação, design, fabricação e a história cultural do anel de noivado com diamante.',
    youtubeId: 'N5kWu1ifBGU',
    duration: '42 min',
    year: 2021,
    language: 'Inglês',
    subtitles: 'PT-BR (auto)',
    categories: ['joalheria', 'diamantes'],
    rating: 4.6,
    source: 'Vox',
  },
  {
    id: 'v305',
    title: 'Joias Baratas e Tóxicas — O Lado Sombrio da Bijuteria',
    description: 'A DW investiga a indústria de bijuterias baratas da China: metais pesados, chumbo, cádmio e os riscos para a saúde dos consumidores.',
    youtubeId: 'GFG1INzquMU',
    duration: '42 min',
    year: 2022,
    language: 'Inglês',
    subtitles: 'PT-BR (auto)',
    categories: ['joalheria', 'mercado'],
    rating: 4.3,
    source: 'DW Documentary',
  },
  {
    id: 'v306',
    title: 'Joias e Gemas com Consciência Limpa',
    description: 'Documentário da DW sobre joalheria ética: rastreabilidade de pedras preciosas, ouro fair-trade e o consumidor consciente.',
    youtubeId: 'NsRj-9Y4fZ8',
    duration: '42 min',
    year: 2023,
    language: 'Inglês',
    subtitles: 'PT-BR (auto)',
    categories: ['joalheria', 'gemologia'],
    rating: 4.5,
    source: 'DW Documentary',
  },

  // ═══════════════════════════════════════
  // HISTÓRIA & CIVILIZAÇÕES
  // ═══════════════════════════════════════
  {
    id: 'v601',
    title: 'Tutancâmon — O Faraó Menino e Seu Tesouro',
    description: 'Documentário completo sobre Tutancâmon: a descoberta da tumba, o tesouro de ouro, a máscara mortuária e as técnicas joalheiras do Antigo Egito.',
    youtubeId: 'fw_AokHZz48',
    duration: '1h 30min',
    year: 2021,
    language: 'Inglês',
    subtitles: 'PT-BR (auto)',
    categories: ['historia', 'ouro', 'joalheria'],
    rating: 4.7,
    source: 'The People Profiles',
  },
  {
    id: 'v603',
    title: 'Os Tesouros da Família Real — Joias da Coroa Britânica',
    description: 'Tour completo pelas joias mais valiosas do mundo: a Coroa Imperial, o Koh-i-Noor, o Cullinan e 800 anos de história na Torre de Londres.',
    youtubeId: 'ca41auJln98',
    duration: '48 min',
    year: 2022,
    language: 'Inglês',
    subtitles: 'PT-BR (auto)',
    categories: ['historia', 'joalheria', 'diamantes', 'destaques', 'luxo'],
    rating: 4.8,
    source: 'Real Royalty',
  },

  // ═══════════════════════════════════════
  // OURO — Novos (2026-04-04)
  // ═══════════════════════════════════════
  {
    id: 'v009',
    title: 'Gold Mafia — Episódio 2: Fumaça e Espelhos',
    description: 'Continuação da investigação da Al Jazeera: como redes de lavagem de dinheiro usam o ouro para mover bilhões sem deixar rastro.',
    youtubeId: 'HYIcCoYt9YE',
    duration: '48 min',
    year: 2023,
    language: 'Inglês',
    subtitles: 'PT-BR (auto)',
    categories: ['ouro', 'mineracao', 'mercado'],
    rating: 4.7,
    source: 'Al Jazeera Investigations',
  },
  {
    id: 'v010',
    title: 'Gold Mafia — Episódio 3: El Dorado',
    description: 'Terceiro episódio: o papel de diplomatas e políticos no contrabando de ouro africano. A trilha do dinheiro até os cofres internacionais.',
    youtubeId: 'xP_rhbJHokw',
    duration: '48 min',
    year: 2023,
    language: 'Inglês',
    subtitles: 'PT-BR (auto)',
    categories: ['ouro', 'mineracao', 'mercado'],
    rating: 4.7,
    source: 'Al Jazeera Investigations',
  },
  {
    id: 'v011',
    title: 'Hidden Secrets of Money Ep. 2 — Os 7 Estágios do Império',
    description: 'Mike Maloney analisa os ciclos históricos dos impérios e como o ouro e a prata sempre sobrevivem ao colapso das moedas fiduciárias.',
    youtubeId: 'EdSq5H7awi8',
    duration: '30 min',
    year: 2013,
    language: 'Inglês',
    subtitles: 'PT-BR (auto)',
    categories: ['ouro', 'mercado', 'historia'],
    rating: 4.6,
    source: 'GoldSilver',
  },
  {
    id: 'v012',
    title: 'Hidden Secrets of Money Ep. 3 — Desdolarização',
    description: 'A morte do padrão dólar e o papel do ouro na nova ordem monetária mundial. O que acontece quando a moeda de reserva perde credibilidade.',
    youtubeId: 'y-IemeM-Ado',
    duration: '30 min',
    year: 2013,
    language: 'Inglês',
    subtitles: 'PT-BR (auto)',
    categories: ['ouro', 'mercado'],
    rating: 4.5,
    source: 'GoldSilver',
  },
  {
    id: 'v013',
    title: 'Hidden Secrets of Money Ep. 4 — O Maior Golpe da História',
    description: 'Como o sistema bancário de reserva fracionária cria dinheiro do nada e por que o ouro é o antídoto contra a inflação sistêmica.',
    youtubeId: 'iFDe5kUUyT0',
    duration: '30 min',
    year: 2013,
    language: 'Inglês',
    subtitles: 'PT-BR (auto)',
    categories: ['ouro', 'mercado'],
    rating: 4.7,
    source: 'GoldSilver',
  },
  {
    id: 'v014',
    title: 'End of the Road — Como o Dinheiro Perdeu Valor',
    description: 'Documentário completo sobre a crise financeira, o padrão ouro abandonado e por que os metais preciosos são a última reserva de valor real.',
    youtubeId: 'NJd6RKsY5H4',
    duration: '1h 15min',
    year: 2020,
    language: 'Inglês',
    subtitles: 'PT-BR (auto)',
    categories: ['destaques', 'ouro', 'mercado'],
    rating: 4.6,
    source: 'ENDEVR',
  },

  // ═══════════════════════════════════════
  // PRATA — Novos (2026-04-04)
  // ═══════════════════════════════════════
  {
    id: 'v203',
    title: 'Processo de Mineração da Prata — Do Minério ao Lingote',
    description: 'Como a prata é extraída, refinada e transformada em lingotes. O processo industrial completo da mineração à barra.',
    youtubeId: 'h0n5NPMcd6U',
    duration: '15 min',
    year: 2021,
    language: 'Inglês',
    subtitles: 'PT-BR (auto)',
    categories: ['prata', 'mineracao'],
    rating: 4.3,
    source: 'Millennial Hustler',
  },

  // ═══════════════════════════════════════
  // GEMOLOGIA — Novos (2026-04-04)
  // ═══════════════════════════════════════
  {
    id: 'v806',
    title: 'Rubis de Moçambique — Bênção ou Maldição?',
    description: 'A DW investiga a mineração de rubis em Moçambique: riqueza mineral, conflito armado e o impacto nas comunidades locais.',
    youtubeId: '3Rv6jBhv7JE',
    duration: '42 min',
    year: 2023,
    language: 'Inglês',
    subtitles: 'PT-BR (auto)',
    categories: ['gemologia', 'mineracao', 'destaques'],
    rating: 4.6,
    source: 'DW Documentary',
  },
  {
    id: 'v807',
    title: 'As Safiras de Caxemira',
    description: 'Documentário sobre as lendárias safiras azuis da Caxemira: as mais raras e valiosas do mundo, e a história das minas no Himalaia.',
    youtubeId: 'JWVgWxltAxQ',
    duration: '52 min',
    year: 2019,
    language: 'Francês',
    subtitles: 'PT-BR (auto)',
    categories: ['gemologia', 'mineracao'],
    rating: 4.5,
    source: 'Patrick Voillot',
  },
  {
    id: 'v808',
    title: 'Esmeraldas da Colômbia — Dentro do Comércio de Gemas',
    description: 'Documentário da CNA dentro das minas de esmeraldas colombianas: garimpeiros, traficantes e as pedras mais verdes do planeta.',
    youtubeId: 'bTWBOMzNR6U',
    duration: '48 min',
    year: 2022,
    language: 'Inglês',
    subtitles: 'PT-BR (auto)',
    categories: ['gemologia', 'mineracao', 'destaques'],
    rating: 4.7,
    source: 'CNA Insider',
  },
  {
    id: 'v809',
    title: 'Guia do GIA — Como Avaliar um Diamante em 4 Minutos',
    description: 'O Gemological Institute of America ensina os 4 Cs de forma rápida e prática: Carat, Color, Clarity e Cut.',
    youtubeId: 'tXdPlZPI9qM',
    duration: '4 min',
    year: 2021,
    language: 'Inglês',
    subtitles: 'PT-BR (auto)',
    categories: ['gemologia', 'diamantes'],
    rating: 4.8,
    source: 'GIA',
  },
  {
    id: 'v810',
    title: 'Do Bruto ao Radiante — A História da Lapidação de Gemas',
    description: 'A evolução da arte da lapidação: dos métodos antigos à tecnologia moderna. Como pedras brutas se transformam em obras-primas.',
    youtubeId: 'gOV4rsbutlk',
    duration: '35 min',
    year: 2023,
    language: 'Inglês',
    subtitles: 'PT-BR (auto)',
    categories: ['gemologia', 'joalheria'],
    rating: 4.4,
    source: 'Gemstones',
  },
  {
    id: 'v811',
    title: 'Blue Ep. 3: Ingenuidade — Documentário de Lapidação',
    description: 'Episódio sobre a arte e ciência do facetamento de gemas. Lapidários mestres mostram técnicas que transformam pedras brutas em jóias.',
    youtubeId: 'OAG0YLpQPNQ',
    duration: '30 min',
    year: 2022,
    language: 'Inglês',
    subtitles: 'PT-BR (auto)',
    categories: ['gemologia', 'joalheria'],
    rating: 4.5,
    source: 'Justin K Prim',
  },
  {
    id: 'v812',
    title: 'Pérolas Negras do Tahiti — Tesouro Enraizado na Tradição',
    description: 'Documentário completo sobre a perlicultura no Tahiti: como as pérolas negras são cultivadas, colhidas e classificadas.',
    youtubeId: '650werQdYZ0',
    duration: '50 min',
    year: 2022,
    language: 'Inglês',
    subtitles: 'PT-BR (auto)',
    categories: ['gemologia', 'destaques'],
    rating: 4.6,
    source: 'SLICE',
  },

  // ═══════════════════════════════════════
  // LUXO — Novos (2026-04-04)
  // ═══════════════════════════════════════
  {
    id: 'v706',
    title: 'Cartier — História do Design de Joalheria (Christie\'s)',
    description: 'A Christie\'s Education explora a história da maison Cartier: do primeiro relógio de pulso ao Panthère, passando pelas peças Art Déco.',
    youtubeId: 'emhcZXA5AbU',
    duration: '18 min',
    year: 2020,
    language: 'Inglês',
    subtitles: 'PT-BR (auto)',
    categories: ['luxo', 'joalheria', 'historia'],
    rating: 4.7,
    source: 'Christie\'s',
  },
  {
    id: 'v707',
    title: 'O Diamante Tiffany — A Pedra Única',
    description: 'A história do lendário Tiffany Diamond: 128 quilates, amarelo canário, usado por Audrey Hepburn e Lady Gaga. A joia mais famosa do mundo.',
    youtubeId: 's7m08mbHmv0',
    duration: '10 min',
    year: 2019,
    language: 'Inglês',
    subtitles: 'PT-BR (auto)',
    categories: ['luxo', 'diamantes'],
    rating: 4.6,
    source: 'Tiffany & Co',
  },
  {
    id: 'v708',
    title: 'Van Cleef & Arpels — O Legado Deslumbrante',
    description: 'Sotheby\'s explora a herança da Van Cleef & Arpels: o Mystery Setting, as peças Alhambra e mais de 100 anos de alta joalheria francesa.',
    youtubeId: 'rwMARITFbnY',
    duration: '22 min',
    year: 2021,
    language: 'Inglês',
    subtitles: 'PT-BR (auto)',
    categories: ['luxo', 'joalheria'],
    rating: 4.5,
    source: 'Sotheby\'s',
  },

  // ═══════════════════════════════════════
  // FILMES (Trailers oficiais verificados)
  // ═══════════════════════════════════════
  {
    id: 'f001',
    title: 'Blood Diamond (Diamante de Sangue)',
    description: 'Leonardo DiCaprio em Serra Leoa durante a guerra civil. Um pescador, um mercenário e um diamante rosa raro. O filme que expôs o comércio de diamantes de conflito ao mundo.',
    youtubeId: 'yknIZsvQjG4',
    duration: '2h 23min',
    year: 2006,
    language: 'Inglês',
    subtitles: 'PT-BR (auto)',
    categories: ['filmes', 'destaques', 'diamantes'],
    rating: 4.8,
    source: 'Warner Bros',
    type: 'filme',
  },
  {
    id: 'f002',
    title: 'Gold (Ouro)',
    description: 'Matthew McConaughey interpreta um prospector que descobre a maior jazida de ouro da Indonésia. Baseado no escândalo real da Bre-X, uma das maiores fraudes minerais da história.',
    youtubeId: 'gdLXPv5NsA4',
    duration: '2h 01min',
    year: 2016,
    language: 'Inglês',
    subtitles: 'PT-BR (auto)',
    categories: ['filmes', 'ouro', 'mineracao'],
    rating: 4.3,
    source: 'TWC-Dimension',
    type: 'filme',
  },
  {
    id: 'f003',
    title: 'Uncut Gems (Joias Brutas)',
    description: 'Adam Sandler como um joalheiro do Diamond District de Nova York, viciado em apostas, que arrisca tudo numa opala negra rara da Etiópia. Thriller eletrizante dos irmãos Safdie.',
    youtubeId: 'vTfJp2Ts9X8',
    duration: '2h 15min',
    year: 2019,
    language: 'Inglês',
    subtitles: 'PT-BR (auto)',
    categories: ['filmes', 'destaques', 'gemologia', 'joalheria'],
    rating: 4.7,
    source: 'A24',
    type: 'filme',
  },
  {
    id: 'f004',
    title: 'The Gold Rush (Em Busca do Ouro) — Charlie Chaplin',
    description: 'O clássico imortal de Chaplin (1925). Carlitos na corrida do ouro do Klondike. Comédia, poesia e a dança dos pãezinhos. Domínio público.',
    youtubeId: 'DJwOpY84Oq4',
    duration: '1h 35min',
    year: 1925,
    language: 'Mudo',
    subtitles: 'Intertítulos',
    categories: ['filmes', 'ouro', 'historia'],
    rating: 4.9,
    source: 'mk2 Films',
    type: 'filme',
  },
  {
    id: 'f005',
    title: 'Goldfinger — James Bond 007',
    description: 'O vilão Auric Goldfinger planeja contaminar o ouro de Fort Knox com radiação para multiplicar o valor do seu próprio estoque. O Bond clássico que definiu a franquia.',
    youtubeId: 'MA65V-oLKa8',
    duration: '1h 50min',
    year: 1964,
    language: 'Inglês',
    subtitles: 'PT-BR (auto)',
    categories: ['filmes', 'ouro'],
    rating: 4.6,
    source: 'MGM / United Artists',
    type: 'filme',
  },
  {
    id: 'f006',
    title: 'Ocean\'s 8 — As Golpistas',
    description: 'Sandra Bullock lidera um time feminino para roubar um colar Cartier de US$ 150 milhões durante o Met Gala. Alta joalheria, moda e o maior roubo de joias do cinema.',
    youtubeId: 'n5LoVcVsiSQ',
    duration: '1h 50min',
    year: 2018,
    language: 'Inglês',
    subtitles: 'PT-BR (auto)',
    categories: ['filmes', 'joalheria', 'luxo'],
    rating: 4.2,
    source: 'Warner Bros',
    type: 'filme',
  },
  {
    id: 'f007',
    title: 'The Treasure of the Sierra Madre (O Tesouro de Sierra Madre)',
    description: 'Humphrey Bogart em busca de ouro no México. A ganância, a paranoia e a famosa frase "We don\'t need no stinking badges!". Clássico vencedor de 3 Oscars.',
    youtubeId: 'GME0jQyM0Fc',
    duration: '2h 06min',
    year: 1948,
    language: 'Inglês',
    subtitles: 'PT-BR (auto)',
    categories: ['filmes', 'ouro', 'historia'],
    rating: 4.8,
    source: 'Warner Bros',
    type: 'filme',
  },
  {
    id: 'f008',
    title: 'Breakfast at Tiffany\'s (Bonequinha de Luxo)',
    description: 'Audrey Hepburn como Holly Golightly tomando café diante da vitrine da Tiffany & Co. O filme que transformou a joalheria em ícone do cinema e da cultura pop.',
    youtubeId: 'KlZ4fYqjGJI',
    duration: '1h 55min',
    year: 1961,
    language: 'Inglês',
    subtitles: 'PT-BR (auto)',
    categories: ['filmes', 'destaques', 'luxo', 'joalheria'],
    rating: 4.9,
    source: 'Paramount Pictures',
    type: 'filme',
  },
  {
    id: 'f009',
    title: 'Serra Pelada — O Filme',
    description: 'Drama brasileiro baseado na história real do maior garimpo de ouro a céu aberto do mundo, no Pará dos anos 80. Lama, sonhos e a febre do ouro brasileira.',
    youtubeId: 'HdmNSPvPkhE',
    duration: '1h 40min',
    year: 2013,
    language: 'Português',
    subtitles: 'Nativo',
    categories: ['filmes', 'destaques', 'ouro', 'mineracao'],
    rating: 4.3,
    source: 'Tatui Filmes',
    type: 'filme',
  },
  {
    id: 'f010',
    title: 'Diamantes São Eternos — 007',
    description: 'Sean Connery como James Bond infiltrado no contrabando de diamantes de Amsterdã a Las Vegas. A conexão entre diamantes africanos e o crime organizado.',
    youtubeId: 'eblH_hfmOS4',
    duration: '2h 00min',
    year: 1971,
    language: 'Inglês',
    subtitles: 'PT-BR (auto)',
    categories: ['filmes', 'diamantes'],
    rating: 4.3,
    source: 'MGM / United Artists',
    type: 'filme',
  },
  {
    id: 'f011',
    title: 'The Pink Panther (A Pantera Cor-de-Rosa)',
    description: 'Peter Sellers como o Inspetor Clouseau atrás do maior diamante do mundo. A comédia que criou uma lenda e provou que um diamante rosa pode ser mais engraçado que valioso.',
    youtubeId: '-Dy-Gb3LaFE',
    duration: '1h 55min',
    year: 1963,
    language: 'Inglês',
    subtitles: 'PT-BR (auto)',
    categories: ['filmes', 'diamantes'],
    rating: 4.5,
    source: 'United Artists',
    type: 'filme',
  },
  {
    id: 'f012',
    title: 'Gentlemen Prefer Blondes (Os Homens Preferem as Loiras)',
    description: 'Marilyn Monroe canta "Diamonds Are a Girl\'s Best Friend" neste clássico. O filme que tornou os diamantes sinônimo de glamour hollywoodiano.',
    youtubeId: 'TOqfJEPB8rI',
    duration: '1h 31min',
    year: 1953,
    language: 'Inglês',
    subtitles: 'PT-BR (auto)',
    categories: ['filmes', 'diamantes', 'historia'],
    rating: 4.6,
    source: '20th Century Fox',
    type: 'filme',
  },
  {
    id: 'f013',
    title: 'How to Steal a Million (Como Roubar Um Milhão)',
    description: 'Audrey Hepburn e Peter O\'Toole planejam roubar uma estátua com diamantes de um museu em Paris. Elegância, humor e joias falsas.',
    youtubeId: 'UPStHOzjQWU',
    duration: '2h 03min',
    year: 1966,
    language: 'Inglês',
    subtitles: 'PT-BR (auto)',
    categories: ['filmes', 'joalheria', 'luxo'],
    rating: 4.5,
    source: '20th Century Fox',
    type: 'filme',
  },
  {
    id: 'f014',
    title: 'Fool\'s Gold (O Tesouro Encalhado)',
    description: 'Matthew McConaughey e Kate Hudson caçam um tesouro espanhol de ouro e esmeraldas no Caribe. Aventura leve com joias históricas.',
    youtubeId: 'LNckeLY3Kkw',
    duration: '1h 52min',
    year: 2008,
    language: 'Inglês',
    subtitles: 'PT-BR (auto)',
    categories: ['filmes', 'ouro'],
    rating: 3.9,
    source: 'Warner Bros',
    type: 'filme',
  },
  {
    id: 'f015',
    title: 'Romancing the Stone (A Joia do Nilo)',
    description: 'Michael Douglas e Kathleen Turner numa aventura na Colômbia atrás de uma esmeralda gigante. Ação, romance e a maior pedra verde do cinema.',
    youtubeId: 'DL40GuLfxA8',
    duration: '1h 46min',
    year: 1984,
    language: 'Inglês',
    subtitles: 'PT-BR (auto)',
    categories: ['filmes', 'gemologia'],
    rating: 4.4,
    source: '20th Century Fox',
    type: 'filme',
  },
];
